{
  "uid" : "51b462a8271bf02c",
  "name" : "Incorrect authorization",
  "fullName" : "tests.incorrect_authorization_test.TestIncorrectProfile#test_incorrect_authorization_page",
  "historyId" : "1b3f37e102b00e7a3fb371a5d738e0ab",
  "time" : {
    "start" : 1707910007500,
    "stop" : 1707910007500,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "TypeError: WebDriver.__init__() got multiple values for argument 'options'",
  "statusTrace" : "request = <SubRequest 'driver' for <Function test_incorrect_authorization_page>>\n\n    @pytest.fixture(scope=\"function\", autouse=True)\n    def driver(request):\n        options = Options()\n        options.add_argument(\"--no-sandbox\")\n        options.add_argument(\"--headless\")\n        options.add_argument(\"--disable-dev-shm-usage\")\n        options.add_argument(\"--window-size=1024,768\")\n        options.add_argument(\"--user-data-dir=chrome-data\")\n>       driver = webdriver.Chrome('chromedriver.exe', options=options)\nE       TypeError: WebDriver.__init__() got multiple values for argument 'options'\n\nconftest.py:14: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver",
    "time" : {
      "start" : 1707910007501,
      "stop" : 1707910007501,
      "duration" : 0
    },
    "status" : "broken",
    "statusMessage" : "TypeError: WebDriver.__init__() got multiple values for argument 'options'\n",
    "statusTrace" : "  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1149, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 916, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 14, in driver\n    driver = webdriver.Chrome('chromedriver.exe', options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Personal incorrect authorization page"
  }, {
    "name" : "severity",
    "value" : "Critical"
  }, {
    "name" : "tag",
    "value" : "smoke"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "incorrect_authorization_test"
  }, {
    "name" : "subSuite",
    "value" : "TestIncorrectProfile"
  }, {
    "name" : "host",
    "value" : "28c15affdd8c"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.incorrect_authorization_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "critical",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "smoke" ]
  },
  "source" : "51b462a8271bf02c.json",
  "parameterValues" : [ ]
}